name: FlavorFlow Apply Flavor Configuration
description: Apply complete flavor configuration including branding, assets, and environment variables. See https://flavorflow.io

branding:
  icon: smartphone
  color: purple

inputs:
  flavor:
    description: 'The flavor JSON object containing branding information'
    required: true

  project-api-key:
    description: 'The project API key to fetch additional resources if needed'
    required: true

  assets-destination:
    description: 'Directory where assets should be downloaded'
    required: false
    default: './assets'

  project-type:
    description: 'The type of project to apply flavor to (android-native-compose, android-native-xml)'
    required: false

outputs:
  status:
    description: 'Status of the branding application'
  
  flavor-name:
    description: 'Name of the applied flavor'
    
  package-name:
    description: 'Package name that was applied'
    
  logo-path:
    description: 'Path to the downloaded logo file'
    
  assets-downloaded:
    description: 'Number of assets that were downloaded'
    
  variables-set:
    description: 'Number of environment variables that were set'
    
  project-type:
    description: 'Project type that was used (actual or detected)'

runs:
  using: node20
  main: dist/index.js