name: Prisme Apply Branding Android
description: Apply branding configuration for a specific flavor

branding:
  icon: smartphone
  color: purple

inputs:
  flavor:
    description: 'The flavor JSON object containing branding information'
    required: true

  project-api-key:
    description: 'The project API key to fetch additional resources if needed'
    required: true

outputs:
  status:
    description: 'Status of the branding application'

runs:
  using: node20
  main: dist/index.js