name: Apply Branding
description: Apply branding configuration for a specific flavor automatically from environment variables

outputs:
  status:
    description: 'Status of the branding application'

runs:
  using: node20
  main: dist/index.js